-- documents.embedding 에 HNSW 인덱스를 켠다 (RAG-084 · D16 · #384)
--
-- `db/indexes.sql` 이 2026-08 부터 이 문장을 들고 있었는데 "적재가 끝난 뒤 수동" 이라고만
-- 적혀 있어서 **아무도 안 돌렸다.** 2026-09-09 실측으로 `documents` 에는 인덱스가 넷
-- (`idx_documents_cat` · `_meta` · `_tsv` · `_org`) 있고 embedding 것만 없다.
--
-- ⚠️ **혼자 오면 손해다.** `rag load` 가 매번 전 행을 upsert 하던 동안에는 이 인덱스를 켜는
-- 순간 **매일 그래프를 통째로 갈아 내게 된다.** 짝은 적재 증분화이고 같은 카드(#384)에 있다 —
-- `load.py` 의 `ON CONFLICT DO UPDATE ... WHERE ... IS DISTINCT FROM`. **코드가 먼저 배포된
-- 다음에 이 파일을 적용하라.** 순서가 반대면 하루치 재적재가 통째로 인덱스를 간다.
--   (`db/migrations/README.md` 는 보통 마이그레이션을 **먼저** 적용하라고 한다. 그 규칙은
--    "없는 컬럼을 SELECT 해서 500 이 난다"를 막는 것이고, 이 장은 컬럼이 아니라 **비용**의
--    문제라 방향이 반대다.)
--
-- ⚠️ **적용 계정을 먼저 확인하라.** `CREATE INDEX` 는 표 소유자(또는 슈퍼유저)만 할 수 있다.
-- 한 줄이면 갈린다 — 둘 중 하나만 맞으면 그냥 적용하면 된다:
--
--   SELECT pg_get_userbyid(relowner) AS owner FROM pg_class WHERE relname = 'documents';
--   SELECT usesuper FROM pg_user WHERE usename = current_user;
--
-- 왜 확인부터인가 — `db/migrations/README.md` 의 「표 일부는 postgres 소유다」(2026-09-08 · #329)가
-- *"`daengs` 는 슈퍼유저가 아니고 `documents`·`crawl_runs` 는 `postgres` 소유"* 라고 적어 두었다.
-- **그런데 2026-09-09 에 사람은 `daengs` 도 슈퍼유저이고 여태 그 계정으로 해 왔다고 했다.**
-- 둘 중 하나가 낡았고, 서버 DB 를 못 본 채로는 가릴 수 없어서 단정하지 않는다
-- (그날 서버 PC 가 꺼져 있었다). 맞는 쪽을 확인했으면 **README 의 그 절을 같이 고쳐라.**
--
-- 슈퍼유저가 아니고 소유자도 아니라면 `db-migrate.yml`(= `$POSTGRES_USER` 로 붙는다)로는 안 되고,
-- 서버 PC 에서 둘 중 하나로 간다:
--
--   docker exec -i pgvector psql -U postgres -d vectordb -f - < db/migrations/2026-09-09_documents_hnsw.sql
--   docker exec -i pgvector psql -U postgres -d vectordb -c "ALTER TABLE documents OWNER TO daengs;"
--
-- GCP 는 사람이 프로젝트 소유자이고 SSH 로 들어간다 — 권한 문제가 없다 (2026-09-09 사람).
--
-- ⚠️ **`CONCURRENTLY` 를 안 쓴다.** 빌드 동안 표가 쓰기 잠금에 걸리지만, 이 표에 쓰는 것은
-- 사람이 돌리는 `rag load` 와 GCP 잡(KST 04:00) 하나뿐이라 그 시간을 피하면 된다.
-- `CONCURRENTLY` 는 트랜잭션 안에서 못 돌고 실패하면 invalid 인덱스를 남기는데, 그 뒷정리가
-- 버전 테이블 없는 이 저장소에서 더 비싸다.
--
-- ⚠️ **연산자 클래스는 `vector_cosine_ops` 여야 한다.** 검색이 `<=>`(코사인)로 물어서다.
-- `<->` 나 `<#>` 용으로 만들면 **인덱스가 그냥 안 타고, 결과는 맞고 느려지기만 해서
-- 아무도 안 알려준다** (`db/indexes.sql` 이 같은 경고를 달고 있다).
--
-- ⚠️ **근사 검색이라 기준선이 이동한다.** `hnsw.ef_search` 기본값은 40 인데 검색은 축마다
-- 후보 100개를 뽑는다(`CANDIDATE_N`) — 그대로 두면 100개를 채우지 못해 recall 이 떨어진다.
-- 값과 대가는 카드(#384)에서 잰다.
--
-- 여러 번 돌려도 안전하다 (`IF NOT EXISTS`).

CREATE INDEX IF NOT EXISTS idx_documents_embedding ON documents
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);
