"""Finite vocabulary for spatial material candidates, before scene admission.

Land codes: https://aid.mcee.go.kr/intro/land.do (2026-09-13).
Commerce groups use the SDSC major codes; I212 is the beverage subdivision.
The vocabulary describes background material, not dog actions or crowding.
"""

LAND_TYPES = {
    "111": "단독주거시설",
    "112": "공동주거시설",
    "121": "공업시설",
    "131": "상업·업무시설",
    "132": "혼합지역",
    "141": "문화·체육·휴양시설",
    "151": "공항",
    "152": "항만",
    "153": "철도",
    "154": "도로",
    "155": "기타 교통·통신시설",
    "161": "환경기초시설",
    "162": "교육·행정시설",
    "163": "기타 공공시설",
    "211": "경지정리가 된 논",
    "212": "경지정리가 안 된 논",
    "221": "경지정리가 된 밭",
    "222": "경지정리가 안 된 밭",
    "231": "시설재배지",
    "241": "과수원",
    "251": "목장·양식장",
    "252": "기타재배지",
    "311": "활엽수림",
    "321": "침엽수림",
    "331": "혼효림",
    "411": "자연초지",
    "421": "골프장",
    "422": "묘지",
    "423": "기타초지",
    "511": "내륙습지",
    "521": "갯벌",
    "522": "염전",
    "611": "해변",
    "612": "강기슭",
    "613": "암벽·바위",
    "621": "채광지역",
    "622": "운동장",
    "623": "기타나지",
    "711": "하천",
    "712": "호소",
    "721": "해양수",
}
PARK_TYPES = (
    "소공원",
    "어린이공원",
    "근린공원",
    "역사공원",
    "문화공원",
    "수변공원",
    "묘지공원",
    "체육공원",
    "도시농업공원",
    "방재공원",
    "기타",
)
COMMERCE_GROUPS = {
    "G2": "retail",
    "I1": "lodging",
    "I2": "food",
    "L1": "real_estate",
    "M1": "professional",
    "N1": "business_support",
    "P1": "education",
    "Q1": "health",
    "R1": "arts_sports",
    "S2": "personal_service",
}
COMPOSITION = {
    "retail": "소매점 중심",
    "lodging": "숙박업소 중심",
    "food": "음식점·카페 중심",
    "beverage": "카페·음료점 중심",
    "real_estate": "부동산업소 중심",
    "professional": "전문 서비스업종 중심",
    "business_support": "사업지원·임대업종 중심",
    "education": "교육업종 중심",
    "health": "보건의료업종 중심",
    "arts_sports": "예술·스포츠업종 중심",
    "personal_service": "수리·개인서비스업종 중심",
    "mixed": "여러 업종 혼합",
}
CASES = {
    **{f"land_cover:{code}": {"피복": label} for code, label in LAND_TYPES.items()},
    **{f"park:{kind}": {"공원종류": kind} for kind in PARK_TYPES},
    "park:unspecified": {"공원종류": "공원"},
    **{f"commerce:{key}": {"업종구성": label} for key, label in COMPOSITION.items()},
    "commerce:sparse": {"분포": "등록 상가가 적은 구간"},
    "commerce:clustered": {"분포": "등록 상가가 모인 구간"},
    "commerce:scattered": {"분포": "등록 상가가 산재한 구간"},
}
